import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faClone } from '@fortawesome/free-regular-svg-icons'

import { css } from "styled-system/css";
import { Box, Stack, HStack, Flex, styled, Center } from "styled-system/jsx";
import { Collapsible } from '~/components/ui/collapsible'
import { Button } from '~/components/ui/button'
import { Text } from '~/components/ui/text'
import { Popover, Tooltip } from '@ark-ui/react'
import { faXmark } from '@fortawesome/free-solid-svg-icons'
import { Heading } from '~/components/ui/heading'
import Navbar from "./components_custom/Navbar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={css({
          backgroundColor: "background",
        })}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}